import type { Listing } from "./ListingCard";

export type ListingWithMeta = Listing & {
  priceValue: number;
  createdOrder: number; // для сортировки по дате (меньше = старее или новее в зависимости от режима)
  priorityWeight: number;
};

export const mockListings: ListingWithMeta[] = [
  {
    id: 1,
    title: "Игровой ноутбук для учебы и работы",
    price: "89 000 ₽",
    category: "Электроника",
    status: "pending",
    priority: "urgent",
    createdAt: "сегодня, 12:30",
    image: "https://via.placeholder.com/320x200",
    priceValue: 89000,
    createdOrder: 1,
    priorityWeight: 2,
  },
  {
    id: 2,
    title: "Стол рабочий + кресло",
    price: "12 500 ₽",
    category: "Мебель",
    status: "approved",
    priority: "normal",
    createdAt: "вчера, 19:10",
    image: "https://via.placeholder.com/320x200",
    priceValue: 12500,
    createdOrder: 3,
    priorityWeight: 1,
  },
  {
    id: 3,
    title: 'Монитор 27" IPS 144 Hz',
    price: "24 900 ₽",
    category: "Электроника",
    status: "rejected",
    priority: "normal",
    createdAt: "2 дня назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 24900,
    createdOrder: 5,
    priorityWeight: 1,
  },
  {
    id: 4,
    title: "Смартфон с отличной камерой",
    price: "34 000 ₽",
    category: "Электроника",
    status: "pending",
    priority: "normal",
    createdAt: "сегодня, 09:05",
    image: "https://via.placeholder.com/320x200",
    priceValue: 34000,
    createdOrder: 2,
    priorityWeight: 1,
  },
  {
    id: 5,
    title: "Кресло игровое",
    price: "18 300 ₽",
    category: "Мебель",
    status: "pending",
    priority: "urgent",
    createdAt: "вчера, 21:47",
    image: "https://via.placeholder.com/320x200",
    priceValue: 18300,
    createdOrder: 4,
    priorityWeight: 2,
  },
  {
    id: 6,
    title: "Настольная лампа",
    price: "1 500 ₽",
    category: "Мебель",
    status: "approved",
    priority: "normal",
    createdAt: "3 дня назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 1500,
    createdOrder: 7,
    priorityWeight: 1,
  },
  {
    id: 7,
    title: "Куртка зимняя мужская",
    price: "7 900 ₽",
    category: "Одежда",
    status: "pending",
    priority: "normal",
    createdAt: "сегодня, 08:10",
    image: "https://via.placeholder.com/320x200",
    priceValue: 7900,
    createdOrder: 2,
    priorityWeight: 1,
  },
  {
    id: 8,
    title: "Платье вечернее",
    price: "5 200 ₽",
    category: "Одежда",
    status: "approved",
    priority: "urgent",
    createdAt: "вчера, 11:00",
    image: "https://via.placeholder.com/320x200",
    priceValue: 5200,
    createdOrder: 3,
    priorityWeight: 2,
  },
  {
    id: 9,
    title: "Услуги репетитора по математике",
    price: "1 200 ₽",
    category: "Услуги",
    status: "pending",
    priority: "normal",
    createdAt: "2 дня назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 1200,
    createdOrder: 5,
    priorityWeight: 1,
  },
  {
    id: 10,
    title: "Уборка квартир",
    price: "2 000 ₽",
    category: "Услуги",
    status: "rejected",
    priority: "normal",
    createdAt: "3 дня назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 2000,
    createdOrder: 7,
    priorityWeight: 1,
  },
  {
    id: 11,
    title: "Ноутбук офисный",
    price: "42 000 ₽",
    category: "Электроника",
    status: "approved",
    priority: "normal",
    createdAt: "4 дня назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 42000,
    createdOrder: 8,
    priorityWeight: 1,
  },
  {
    id: 12,
    title: "Игровая консоль",
    price: "55 000 ₽",
    category: "Электроника",
    status: "pending",
    priority: "urgent",
    createdAt: "сегодня, 13:05",
    image: "https://via.placeholder.com/320x200",
    priceValue: 55000,
    createdOrder: 1,
    priorityWeight: 2,
  },
  {
    id: 13,
    title: "Кофейный столик",
    price: "6 800 ₽",
    category: "Мебель",
    status: "approved",
    priority: "normal",
    createdAt: "5 дней назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 6800,
    createdOrder: 9,
    priorityWeight: 1,
  },
  {
    id: 14,
    title: "Шкаф-купе",
    price: "23 000 ₽",
    category: "Мебель",
    status: "pending",
    priority: "normal",
    createdAt: "4 дня назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 23000,
    createdOrder: 8,
    priorityWeight: 1,
  },
  {
    id: 15,
    title: "Джинсы мужские",
    price: "2 900 ₽",
    category: "Одежда",
    status: "approved",
    priority: "normal",
    createdAt: "5 дней назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 2900,
    createdOrder: 9,
    priorityWeight: 1,
  },
  {
    id: 16,
    title: "Кроссовки женские",
    price: "4 300 ₽",
    category: "Одежда",
    status: "pending",
    priority: "urgent",
    createdAt: "сегодня, 07:45",
    image: "https://via.placeholder.com/320x200",
    priceValue: 4300,
    createdOrder: 2,
    priorityWeight: 2,
  },
  {
    id: 17,
    title: "Ремонт ноутбуков",
    price: "0 ₽",
    category: "Услуги",
    status: "pending",
    priority: "normal",
    createdAt: "2 дня назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 0,
    createdOrder: 5,
    priorityWeight: 1,
  },
  {
    id: 18,
    title: "Фотосъёмка мероприятий",
    price: "3 500 ₽",
    category: "Услуги",
    status: "approved",
    priority: "normal",
    createdAt: "3 дня назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 3500,
    createdOrder: 7,
    priorityWeight: 1,
  },
  {
    id: 19,
    title: "Игровое кресло с подставкой",
    price: "21 700 ₽",
    category: "Мебель",
    status: "rejected",
    priority: "urgent",
    createdAt: "вчера, 16:40",
    image: "https://via.placeholder.com/320x200",
    priceValue: 21700,
    createdOrder: 3,
    priorityWeight: 2,
  },
  {
    id: 20,
    title: "Смарт-часы",
    price: "9 900 ₽",
    category: "Электроника",
    status: "approved",
    priority: "normal",
    createdAt: "6 дней назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 9900,
    createdOrder: 10,
    priorityWeight: 1,
  },
  {
    id: 21,
    title: "Пуховик женский",
    price: "8 500 ₽",
    category: "Одежда",
    status: "pending",
    priority: "normal",
    createdAt: "вчера, 18:20",
    image: "https://via.placeholder.com/320x200",
    priceValue: 8500,
    createdOrder: 3,
    priorityWeight: 1,
  },
  {
    id: 22,
    title: "Настройка ПК и сетей",
    price: "1 800 ₽",
    category: "Услуги",
    status: "approved",
    priority: "normal",
    createdAt: "4 дня назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 1800,
    createdOrder: 8,
    priorityWeight: 1,
  },
  {
    id: 23,
    title: "Телевизор 4K 55\"",
    price: "64 000 ₽",
    category: "Электроника",
    status: "pending",
    priority: "urgent",
    createdAt: "сегодня, 10:50",
    image: "https://via.placeholder.com/320x200",
    priceValue: 64000,
    createdOrder: 1,
    priorityWeight: 2,
  },
  {
    id: 24,
    title: "Диван угловой",
    price: "39 900 ₽",
    category: "Мебель",
    status: "approved",
    priority: "normal",
    createdAt: "6 дней назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 39900,
    createdOrder: 10,
    priorityWeight: 1,
  },
  {
    id: 25,
    title: "Футболка базовая",
    price: "900 ₽",
    category: "Одежда",
    status: "rejected",
    priority: "normal",
    createdAt: "5 дней назад",
    image: "https://via.placeholder.com/320x200",
    priceValue: 900,
    createdOrder: 9,
    priorityWeight: 1,
  },
];
